export enum GameCategory {
  Featured = 'featured',
  Football = 'football',
  Tennis = 'tennis',
  Volleyball = 'volleyball',
  Baseball = 'baseball',
  IceHockey = 'iceHockey',
  Handball = 'handball',
  Cricket = 'cricket',
  MMA = 'mma',
  Snooker = 'snooker',
  WaterPolo = 'waterPolo',
  Darts = 'darts',
  Golf = 'golf',
  FormulaOne = 'formulaOne',
  Cycling = 'cycling',
  Chess = 'chess',
  Netball = 'netball',
  Netball1 = 'netball',
  Netball2 = 'netball',
  Netball3 = 'netball',
  Netball4 = 'netball',
  Netball5 = 'netball',
  Netball6 = 'netball',
}

export const gameCategoryNames: Record<GameCategory, string> = {
  [GameCategory.Featured]: 'Featured',
  [GameCategory.Football]: 'Football',
  [GameCategory.Tennis]: 'Tennis',
  [GameCategory.Volleyball]: 'Volleyball',
  [GameCategory.Baseball]: 'Baseball',
  [GameCategory.IceHockey]: 'Ice Hockey',
  [GameCategory.Handball]: 'Handball',
  [GameCategory.Cricket]: 'Cricket',
  [GameCategory.MMA]: 'MMA',
  [GameCategory.Snooker]: 'Snooker',
  [GameCategory.WaterPolo]: 'Water Polo',
  [GameCategory.Darts]: 'Darts',
  [GameCategory.Golf]: 'Golf',
  [GameCategory.FormulaOne]: 'Formula One',
  [GameCategory.Cycling]: 'Cycling',
  [GameCategory.Chess]: 'Chess',
  [GameCategory.Netball]: 'Netball',
};
