---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: 22
    ansible_connection: ssh

develop:
  hosts:
    betnomi-frontend-dev:
      ansible_host: 3.139.104.166

master:
  hosts:
    betnomi-frontend-prod:
      ansible_host: 3.129.194.53
